import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ContentService, DEFAULT_HOME_CONTENT, HomeContent } from '../../core/content.service';

@Component({selector:'app-cms-editor-page',imports:[FormsModule,RouterLink],template:`
  <section class="cms"><header><div><a routerLink="/admin">← Volver al panel</a><p>Contenido / Página principal</p><h1>Editor de portada</h1></div><div><span [class.saved]="status().includes('guardado')">{{status()}}</span><button class="button secondary" (click)="save()">Guardar borrador</button><button class="button" [disabled]="!versionId()" (click)="publish()">Publicar</button></div></header>
  <div class="workspace"><form><fieldset><legend>Barra de anuncio</legend><div class="field"><label for="announcement">Mensaje</label><input id="announcement" maxlength="160" [(ngModel)]="content().announcement" name="announcement"></div></fieldset><fieldset><legend>Hero principal</legend><div class="field"><label for="eyebrow">Antetítulo</label><input id="eyebrow" maxlength="80" [(ngModel)]="content().hero.eyebrow" name="eyebrow"></div><div class="two"><div class="field"><label for="title">Título</label><input id="title" maxlength="80" [(ngModel)]="content().hero.title" name="title"></div><div class="field"><label for="accent">Acento</label><input id="accent" maxlength="80" [(ngModel)]="content().hero.accent" name="accent"></div></div><div class="field"><label for="description">Descripción</label><textarea id="description" maxlength="300" rows="3" [(ngModel)]="content().hero.description" name="description"></textarea></div><div class="field"><label for="cta">Texto del botón</label><input id="cta" maxlength="40" [(ngModel)]="content().hero.ctaLabel" name="cta"></div></fieldset><fieldset><legend>Productos destacados</legend><div class="two"><div class="field"><label for="featured-eyebrow">Antetítulo</label><input id="featured-eyebrow" maxlength="80" [(ngModel)]="content().featured.eyebrow" name="featuredEyebrow"></div><div class="field"><label for="featured-heading">Título</label><input id="featured-heading" maxlength="100" [(ngModel)]="content().featured.heading" name="featuredHeading"></div></div></fieldset><fieldset><legend>Historia de marca</legend><div class="field"><label for="story-heading">Título</label><input id="story-heading" maxlength="120" [(ngModel)]="content().story.heading" name="storyHeading"></div><div class="field"><label for="story-description">Descripción</label><textarea id="story-description" maxlength="500" rows="4" [(ngModel)]="content().story.description" name="storyDescription"></textarea></div></fieldset><p class="safe-note">El editor sólo acepta bloques predefinidos y texto plano. No se permite HTML ni scripts.</p></form><aside><div class="preview-bar"><span>Vista previa</span><button [class.active]="desktop()" (click)="desktop.set(true)">Escritorio</button><button [class.active]="!desktop()" (click)="desktop.set(false)">Móvil</button></div><div class="canvas" [class.mobile]="!desktop()"><div class="announcement">{{content().announcement}}</div><div class="preview-hero"><img src="/assets/images/hero-trama-sur.png" alt=""><div><small>{{content().hero.eyebrow}}</small><h2>{{content().hero.title}}<em>{{content().hero.accent}}</em></h2><p>{{content().hero.description}}</p><b>{{content().hero.ctaLabel}} →</b></div></div><section><small>{{content().featured.eyebrow}}</small><h3>{{content().featured.heading}}</h3><div class="cards"><i></i><i></i><i></i><i></i></div></section></div></aside></div></section>
  `,styleUrl:'./cms-editor.page.scss'})
export class CmsEditorPage{private readonly cms=inject(ContentService);readonly content=signal<HomeContent>(structuredClone(DEFAULT_HOME_CONTENT));readonly versionId=signal('');readonly status=signal('Sin cambios');readonly desktop=signal(true);constructor(){this.cms.draft().subscribe({next:r=>{if(r.draft){try{this.content.set(JSON.parse(r.draft.contentJson) as HomeContent);this.versionId.set(r.draft.id);this.status.set(`Borrador v${r.draft.versionNumber}`)}catch{this.status.set('Borrador inválido')}}},error:()=>this.status.set('Inicia sesión con MFA para editar')})}save():void{this.status.set('Guardando…');this.cms.saveDraft(this.content()).subscribe({next:r=>{this.versionId.set(r.versionId);this.status.set(`Borrador v${r.versionNumber} guardado`)},error:e=>this.status.set(e.status===403?'MFA requerido':'Error al guardar')})}publish():void{if(!this.versionId())return;this.status.set('Publicando…');this.cms.publish(this.versionId(),'Publicación desde editor visual').subscribe({next:()=>this.status.set('Publicado correctamente'),error:e=>this.status.set(e.status===403?'MFA requerido':'Error al publicar')})}}

