import { Component, DestroyRef, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';

interface LegalContent{title:string;updated:string;intro:string;sections:{heading:string;paragraphs:string[]}[]}
const common={updated:'13 de julio de 2026'};
const CONTENT:Record<string,LegalContent>={
  terminos:{...common,title:'Términos y condiciones',intro:'Estas condiciones regulan el uso del sitio y las compras realizadas a Trama Sur en Chile.',sections:[{heading:'Identificación del proveedor',paragraphs:['Antes del lanzamiento se debe completar y validar: razón social, RUT, domicilio, correo de contacto, representante legal y canales de atención. Estos datos deben coincidir con SII, Transbank y el emisor de documentos tributarios.']},{heading:'Formación del consentimiento',paragraphs:['La publicación de productos constituye una invitación a comprar. El contrato se entiende perfeccionado cuando Trama Sur confirma por escrito la aceptación de la orden y envía el comprobante con sus condiciones. No se aceptará una orden sin validación de stock y pago.']},{heading:'Precios, stock y despacho',paragraphs:['Todos los precios se informan en pesos chilenos e incluyen IVA. Antes del pago se muestra el costo total, el despacho y una estimación de entrega. El inventario se reserva temporalmente durante el pago para evitar sobreventa.']},{heading:'Pagos',paragraphs:['Los pagos son procesados por Transbank Webpay Plus. Trama Sur no almacena números de tarjeta ni códigos de seguridad. La confirmación depende de la validación servidor a servidor del estado AUTHORIZED y response_code igual a cero.']} ]},
  privacidad:{...common,title:'Política de privacidad',intro:'Explicamos qué datos tratamos, para qué, durante cuánto tiempo y cómo ejercer tus derechos.',sections:[{heading:'Responsable y finalidades',paragraphs:['Trataremos datos de identificación, contacto, despacho, pedidos, comunicaciones y seguridad para ejecutar el contrato, cumplir obligaciones legales, prevenir fraude y responder solicitudes. El marketing requiere consentimiento separado y revocable.']},{heading:'Pagos y terceros',paragraphs:['Transbank procesa los datos de pago. Proveedores de infraestructura, correo y despacho reciben sólo los datos necesarios bajo contratos de confidencialidad y seguridad. No vendemos datos personales.']},{heading:'Conservación y seguridad',paragraphs:['Los datos se conservan por los plazos tributarios, de garantía, defensa jurídica y prevención de fraude aplicables. Aplicamos cifrado en tránsito, control de acceso por rol, registros de auditoría, copias de seguridad y minimización. Ningún sistema puede garantizar riesgo cero.']},{heading:'Tus derechos',paragraphs:['Puedes solicitar acceso, rectificación, eliminación, bloqueo u oposición cuando corresponda. Antes del 1 de diciembre de 2026 se debe verificar la adecuación final a la Ley 21.719 y su normativa, incluyendo el nuevo régimen institucional.']} ]},
  retracto:{...common,title:'Derecho a retracto',intro:'En compras a distancia puedes arrepentirte dentro del plazo legal, sujeto a las excepciones informadas.',sections:[{heading:'Plazo',paragraphs:['Puedes ejercer el retracto dentro de 10 días contados desde que recibes el producto. Si no recibes la confirmación escrita exigida por ley, el plazo puede extenderse a 90 días.']},{heading:'Cómo ejercerlo',paragraphs:['Escríbenos indicando número de pedido, producto y tu decisión inequívoca. Te entregaremos instrucciones y un comprobante de recepción. Conserva el producto y sus elementos razonablemente necesarios para la devolución.']},{heading:'Reembolsos',paragraphs:['Una vez verificado el cumplimiento legal, restituiremos las sumas pagadas por el medio aplicable y dentro del plazo correspondiente. Las excepciones al retracto sólo se aplicarán cuando estén permitidas e informadas previamente.']} ]},
  'cambios-devoluciones':{...common,title:'Cambios y devoluciones',intro:'Ofrecemos 30 días para cambios voluntarios, además de todos tus derechos legales.',sections:[{heading:'Cambio voluntario',paragraphs:['Puedes solicitar cambio dentro de 30 días con comprobante, producto sin uso y en condiciones de reventa. Esta política comercial no limita la garantía legal ni el retracto.']},{heading:'Problemas con el producto',paragraphs:['Si el producto presenta falla, no es apto para su uso o no corresponde a lo informado, puedes ejercer la garantía legal de seis meses y elegir entre reparación gratuita, cambio o devolución del dinero según la ley.']} ]},
  garantia:{...common,title:'Garantía legal',intro:'La garantía legal protege tu compra durante seis meses desde la recepción.',sections:[{heading:'Tus opciones',paragraphs:['Ante una falla cubierta, puedes elegir reparación gratuita, cambio o devolución del dinero. No exigimos garantías extendidas ni condiciones internas para restringir este derecho.']},{heading:'Atención',paragraphs:['Presenta un documento que acredite la compra. Revisaremos el caso sin derivarte obligatoriamente al fabricante y mantendremos trazabilidad de la solicitud.']} ]},
  despachos:{...common,title:'Despachos y entregas',intro:'Despachamos dentro de Chile con seguimiento y plazos informados antes del pago.',sections:[{heading:'Cobertura y costo',paragraphs:['El costo se calcula antes del pago según destino. El despacho estándar es gratuito desde $79.990. Zonas extremas pueden tener plazos distintos, visibles antes de confirmar.']},{heading:'Seguimiento',paragraphs:['Enviaremos la confirmación y el código de seguimiento al correo registrado. Si existe atraso significativo, podrás contactarnos para revisar el estado y los remedios aplicables.']} ]},
  cookies:{...common,title:'Política de cookies',intro:'Usamos las cookies necesarias para que la tienda funcione y pedimos consentimiento para las opcionales.',sections:[{heading:'Cookies esenciales',paragraphs:['Permiten conservar el carrito, proteger la sesión, prevenir falsificación de solicitudes y recordar tus preferencias de privacidad. No pueden desactivarse sin afectar funciones básicas.']},{heading:'Analítica y marketing',paragraphs:['Permanecen desactivadas hasta que aceptes. El panel de preferencias permitirá revocar el consentimiento con la misma facilidad con que se otorgó.']} ]},
  manifiesto:{...common,title:'Diseño con propósito',intro:'Vestirse bien y moverse con libertad no deberían competir.',sections:[{heading:'Menos, mejor',paragraphs:['Diseñamos colecciones acotadas con utilidad verificable. Preferimos un bolsillo bien ubicado, una costura durable y un tejido apropiado antes que una lista inflada de promesas.']},{heading:'Transparencia práctica',paragraphs:['Informamos materiales, cuidado, precio total y límites reales de cada prestación. No usaremos afirmaciones ambientales o técnicas sin respaldo documentado.']} ]},
  'guia-tallas':{...common,title:'Guía de tallas',intro:'Mide una prenda similar en plano y compara antes de elegir.',sections:[{heading:'Cómo medir',paragraphs:['Pecho: mide de axila a axila y multiplica por dos. Cintura: mide el contorno natural sin apretar. Cadera: toma la parte más ancha. Largo: desde el punto superior hasta el borde. Las medidas específicas de cada producto prevalecen.']} ]},
  ayuda:{...common,title:'Centro de ayuda',intro:'Encuentra respuestas rápidas o contáctanos para una atención humana.',sections:[{heading:'Contacto',paragraphs:['Correo: ayuda@tramasur.cl. Horario referencial: lunes a viernes, 09:00 a 18:00. Antes de producción se deben completar teléfono, domicilio comercial y SLA definitivo.']} ]}
};
@Component({selector:'app-legal-page',imports:[RouterLink],template:`@if(content();as page){<section class="legal"><aside><a routerLink="/legal/terminos">Términos</a><a routerLink="/legal/privacidad">Privacidad</a><a routerLink="/legal/retracto">Retracto</a><a routerLink="/legal/cambios-devoluciones">Cambios y devoluciones</a><a routerLink="/legal/garantia">Garantía legal</a><a routerLink="/legal/despachos">Despachos</a></aside><article><p class="eyebrow">Información transparente</p><h1>{{page.title}}</h1><p class="updated">Última actualización: {{page.updated}}</p><p class="lead">{{page.intro}}</p>@for(section of page.sections;track section.heading){<section><h2>{{section.heading}}</h2>@for(paragraph of section.paragraphs;track paragraph){<p>{{paragraph}}</p>}</section>}<div class="notice"><b>Documento operativo previo al lanzamiento</b><p>El contenido implementa los requisitos identificados, pero debe ser revisado por un abogado chileno con los datos reales de la empresa, productos, logística y tratamiento de datos antes de publicar.</p></div></article></section>}`,styleUrl:'./legal.page.scss'})
export class LegalPage{private readonly route=inject(ActivatedRoute);private readonly destroy=inject(DestroyRef);readonly content=signal<LegalContent>(CONTENT['terminos']);constructor(){this.route.paramMap.pipe(takeUntilDestroyed(this.destroy)).subscribe(p=>this.content.set(CONTENT[p.get('slug')??'terminos']??CONTENT['terminos']))}}
